---
- hosts: testserver
  become: true
  vars:
    ansible_become_pass: edureka
  tasks:
  - name: install git
    apt:
      name: git
      state: present
  - name: Install Chromium
    apt:
      name: chromium-browser
      state: latest